[workspace]
resolver = "3"

members = ["kak-lean","kakoune"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
derive_more = "2.0.1"
indoc = "2.0.7"
thiserror = "2.0.17"
tokio = "1.48.0"

kakoune = { path = "kakoune" }

[workspace.lints.clippy]
pedantic = { level = "deny" }
